### ISSUE TITLE
Debug Setup

### ISSUE THREAD

**Issue by Spegs21** [NordicSemiconductor/pc-nrfconnect-boilerplate#23]
I'm trying to develop an application using this boilerplate, api documentation, and other nrf connect applications as a reference and was wondering if there is a recommended setup for debugging?

The trial and error approach doesn't give much feedback as to why something isn't working.

**Comment by bencefr** [comment]
You have access the usual _devtools_ which you can open at any time by `Ctrl+Shift+I`.
I can also suggest to `npm install electron-react-devtools` in `pc-nrfconnect-core`'s directory, which gives you an extra tab in _devtools_ that I find very helpful.

**Comment by bencefr** [comment]
They are the same, only installed in a different way.

**Comment by Spegs21** [comment]
Thanks! This is helpful.
